disabled = false
languageCode = "ti"
languageName = "ትግርኛ"
weight = 1
title = "ቤተ መጻሕፍቲ ዘርኢ ዛንታ"

[params]
displayName = "TI"
isoCode = "ti"
rtl = false
dateFormat = "2 January 2006"
description = "A library of Solarpunk art and story seeds, visions of an optimistic climate future."
logo = "img/sitelogo.png"
